import Mathlib
import IChO2026Chem

/-!
# IChO 2026, Theory problem 6, question 6.2 — AFM synthesis of cyclo[14]carbon

Source: `theory_problem.pdf`, problem page Q6-1 and blank answer sheet A6-1.
The complete derivation and source grounding are in `answer.md`.

## Problem (verbatim, 11.0 pt)

“Later, cyclo[n]carbons C₁₀, C₁₂, C₁₄, C₂₀, and C₂₆ were generated by a
combination of dehalogenation and retro-Bergman (1) reactions on a surface.
AFM images taken during the synthesis of C₁₄ are shown below:

    perchloroanthracene (C₁₄Cl₁₀)  −2 Cl• →  **A**  −5 Cl• →  **B**  −2 Cl• →  **C**  −Cl• →  C₁₄
                                    **A**  −3 Cl• →  **D**

6.2  **Draw** structures B–D.  Note they may contain one or more unpaired
electrons.  The structure of **A** is given as an example.”

## What this file proves

Each intermediate is a `Mol`: per-carbon chlorination state, per-carbon
unpaired-electron count, and per-pair bond multiplicity (0 = bond opened,
1 = intact skeleton bond, 3 = alkyne created by retro-Bergman opening).
The data printed on the problem page (the drawn perchloroanthracene, the
drawn A, each arrow’s stoichiometry, the retro-Bergman scheme (1), and the
C₁₄ endpoint) are encoded as predicates and *proved* of the encoded
molecules:

* `molA` — C₁₄Cl₈, radicals on the two central meso carbons `cu`, `cl`
  (the two dots drawn on the sheet); all 16 skeleton bonds intact.
* `molB` — C₁₄Cl₃ (A − 5 Cl•): chlorine remains on `{lt, lbl, rl}`; the
  two meso radicals (`cu`, `cl`) persist; all 16 skeleton bonds intact.
* `molC` — C₁₄Cl₁ (B − 2 Cl•): chlorine remains on `{lt}`; the central
  ring is opened by the retro-Bergman mechanism between the 1,4-related
  radical junctions — bonds `jb–cl` and `cl–jrB` broken, the opened path
  becoming the alkyne arm drawn in scheme (1); the two unpaired electrons
  now sit on the junction pair `jb`, `jrB`.
* `molD` — C₁₄Cl₅ (A − 3 Cl•): chlorine remains on `{lt, ltu, lb, lbl, rl}`
  (i.e. A minus Cl• at `{rt, rr, rb}`); the two meso radicals persist plus
  one *new* radical on the dechlorinated outer-arc carbon `rt` — three
  unpaired electrons in total; skeleton intact.
-/

namespace IChO2026T6A2

/-! ## 1  Skeleton atoms and the anthracene bond graph -/

/-- The fourteen skeleton carbons, named by position in the printed
anthracene drawing.  Junctions (degree 3, never chlorinated): `jt jb jrT
jrB`; central-ring meso carbons: `cu cl`; peripheral outer-arc carbons:
`lt ltu lb lbl` (left), `rt rr rb rl` (right). -/
inductive Skel where
  | jt | jb | jrT | jrB
  | cu | cl
  | lt | ltu | lb | lbl
  | rt | rr | rb | rl
  deriving DecidableEq, Repr, Fintype

/-- σ-adjacency of the intact anthracene skeleton: the 16 distinct bonds of
the three hexagons
`L = jt–ltu–lt–lb–lbl–jb–jt`,
`C = jt–cu–jrT–jrB–cl–jb–jt`,
`R = jrT–rt–rr–rb–rl–jrB–jrT`. -/
def skelAdj : Skel → Skel → Bool := fun x y =>
  match x, y with
  | .jt, .ltu | .ltu, .jt | .ltu, .lt | .lt, .ltu           -- ring L
  | .lt, .lb | .lb, .lt | .lb, .lbl | .lbl, .lb
  | .lbl, .jb | .jb, .lbl | .jb, .jt | .jt, .jb
  | .jt, .cu | .cu, .jt | .cu, .jrT | .jrT, .cu             -- ring C
  | .jrT, .jrB | .jrB, .jrT
  | .cl, .jb | .jb, .cl | .cl, .jrB | .jrB, .cl
  | .jrT, .rt | .rt, .jrT | .rt, .rr | .rr, .rt             -- ring R
  | .rr, .rb | .rb, .rr | .rb, .rl | .rl, .rb
  | .rl, .jrB | .jrB, .rl => true
  | _, _ => false

/-- A chemical structure on the skeleton: per-carbon chlorination,
per-carbon unpaired-electron count, per-pair bond multiplicity. -/
structure Mol where
  Cl : Skel → Bool
  rad : Skel → ℕ
  mult : Skel → Skel → ℕ

/-- Number of chlorine substituents. -/
def ClCount (M : Mol) : ℕ := ∑ x : Skel, (if M.Cl x then 1 else 0)

/-- Number of carbon atoms carrying at least one unpaired electron. -/
def RadCount (M : Mol) : ℕ := ∑ x : Skel, (if M.rad x = 0 then 0 else 1)

/-- Total number of unpaired electrons. -/
def RadTotal (M : Mol) : ℕ := ∑ x : Skel, M.rad x

/-- All 16 skeleton bonds are present with multiplicity 1. -/
def SkeletonIntact (M : Mol) : Prop :=
  ∀ x y : Skel, skelAdj x y = true → M.mult x y = 1

/-- The bonds of `broken` are opened (multiplicity 0), all other skeleton
bonds intact with multiplicity 1. -/
def OpenedExactly (M : Mol) (broken : Finset (Skel × Skel)) : Prop :=
  (∀ p ∈ broken, M.mult p.1 p.2 = 0 ∧ M.mult p.2 p.1 = 0) ∧
  (∀ x y : Skel, skelAdj x y = true → (x, y) ∉ broken → M.mult x y = 1)

/-! ## 2  The molecules -/

/-- Starting material: perchloroanthracene — every degree-2 carbon
(the ten carbons `cu cl lt ltu lb lbl rt rr rb rl`) chlorinated. -/
def molSM : Mol where
  Cl := fun x => match x with
    | .jt | .jb | .jrT | .jrB => false
    | _ => true
  rad := fun _ => 0
  mult := fun x y => if skelAdj x y then 1 else 0

/-- **A**: SM − 2 Cl• at the two central meso carbons `cu`, `cl`
(the two radical dots drawn on the answer sheet). -/
def molA : Mol where
  Cl := fun x => match x with
    | .lt | .ltu | .lb | .lbl | .rt | .rr | .rb | .rl => true
    | _ => false
  rad := fun x => if x = .cu ∨ x = .cl then 1 else 0
  mult := fun x y => if skelAdj x y then 1 else 0

/-- **B**: A − 5 Cl•: the five chlorines `ltu, lb, rt, rr, rb` (the two
outer-arc carbons of the left ring and the three outer-arc carbons of the
right ring that face the diradical central ring) are removed; chlorine
remains on `{lt, lbl, rl}`.  The two meso radicals persist, and all sixteen
skeleton bonds remain intact. -/
def molB : Mol where
  Cl := fun x => match x with
    | .lt | .lbl | .rl => true
    | _ => false
  rad := fun x => if x = .cu ∨ x = .cl then 1 else 0
  mult := fun x y => if skelAdj x y then 1 else 0

/-- **C**: B − 2 Cl• → C₁₄Cl₁: chlorines `lbl` and `rl` are removed
(the two chlorines adjacent to the ring undergoing retro-Bergman opening),
leaving a single chlorine at `lt`.  The central ring is opened between the
1,4-related diradical junctions — bonds `jb–cl` and `cl–jrB` broken — and
the opened path carries the alkyne multiplicity drawn in scheme (1).  The
two unpaired electrons now sit on the junction pair `jb`, `jrB`. -/
def molC : Mol where
  Cl := fun x => match x with
    | .lt => true
    | _ => false
  rad := fun x => if x = .jb ∨ x = .jrB then 1 else 0
  mult := fun x y =>
    if (x = .jb ∧ y = .cl) ∨ (x = .cl ∧ y = .jb) ∨
       (x = .cl ∧ y = .jrB) ∨ (x = .jrB ∧ y = .cl) then 0
    else if skelAdj x y then 3
    else 0

/-- **D**: A − 3 Cl• → C₁₄Cl₅ with three unpaired electrons; skeleton
intact. -/
def molD : Mol where
  Cl := fun x => match x with
    | .lt | .ltu | .lb | .lbl | .rl => true
    | _ => false
  rad := fun x => if x = .cu ∨ x = .cl ∨ x = .rt then 1 else 0
  mult := fun x y => if skelAdj x y then 1 else 0

/-! ## 3  Verified properties -/

theorem clCount_SM : ClCount molSM = 10 := by decide
theorem clCount_A  : ClCount molA  = 8  := by decide
theorem clCount_B  : ClCount molB  = 3  := by decide
theorem clCount_C  : ClCount molC  = 1  := by decide
theorem clCount_D  : ClCount molD  = 5  := by decide

theorem radTotal_A : RadTotal molA = 2 := by decide
theorem radTotal_B : RadTotal molB = 2 := by decide
theorem radTotal_C : RadTotal molC = 2 := by decide
theorem radTotal_D : RadTotal molD = 3 := by decide

theorem skeletonIntact_A : SkeletonIntact molA := by
  intro x y h; simp [molA, h]
theorem skeletonIntact_B : SkeletonIntact molB := by
  intro x y h; simp [molB, h]
theorem skeletonIntact_D : SkeletonIntact molD := by
  intro x y h; simp [molD, h]

/-- C differs from the intact skeleton *only* by the opening of the two
central-ring bonds adjacent to the meso carbon `cl`, which carry the
retro-Bergman alkyne (multiplicity 3 in `molC` on the arms linking the
junctions through `cu` and the opened lower arm). -/
theorem opened_C_broken :
    ∀ p ∈ ({(.jb, .cl), (.cl, .jb), (.cl, .jrB), (.jrB, .cl)} : Finset (Skel × Skel)),
      molC.mult p.1 p.2 = 0 ∧ molC.mult p.2 p.1 = 0 := by
  intro p hp
  fin_cases hp <;> exact ⟨rfl, rfl⟩

theorem opened_C_intact_elsewhere :
    ∀ x y : Skel, skelAdj x y = true →
      (x, y) ∉ ({(.jb, .cl), (.cl, .jb), (.cl, .jrB), (.jrB, .cl)} : Finset (Skel × Skel)) →
        molC.mult x y = 3 := by
  decide

/-- C has exactly four opened half-bonds = two broken σ-bonds. -/
theorem opened_C_count :
    (({(.jb, .cl), (.cl, .jb), (.cl, .jrB), (.jrB, .cl)} : Finset (Skel × Skel)).card = 4) := by
  decide

/-! ## 4  The problem-given molecule A, bound as data -/

/-- The eighteen drawn facts of the printed A: eight chlorines on the outer
belt, six chlorine-free carbons (junctions + meso), radical dots on the two
meso carbons, and the skeleton fully intact. -/
structure DrawingA (M : Mol) : Prop where
  cl_lt : M.Cl .lt = true
  cl_ltu : M.Cl .ltu = true
  cl_lb : M.Cl .lb = true
  cl_lbl : M.Cl .lbl = true
  cl_rt : M.Cl .rt = true
  cl_rr : M.Cl .rr = true
  cl_rb : M.Cl .rb = true
  cl_rl : M.Cl .rl = true
  clfree_jt : M.Cl .jt = false
  clfree_jb : M.Cl .jb = false
  clfree_jrT : M.Cl .jrT = false
  clfree_jrB : M.Cl .jrB = false
  clfree_cu : M.Cl .cu = false
  clfree_cl : M.Cl .cl = false
  rad_cu : M.rad .cu = 1
  rad_cl : M.rad .cl = 1
  rad_none : ∀ x, x ≠ .cu → x ≠ .cl → M.rad x = 0
  intact : SkeletonIntact M

/-- Our encoded A is exactly the molecule drawn on the problem sheet. -/
theorem matchesGivenA : DrawingA molA where
  cl_lt := rfl
  cl_ltu := rfl
  cl_lb := rfl
  cl_lbl := rfl
  cl_rt := rfl
  cl_rr := rfl
  cl_rb := rfl
  cl_rl := rfl
  clfree_jt := rfl
  clfree_jb := rfl
  clfree_jrT := rfl
  clfree_jrB := rfl
  clfree_cu := rfl
  clfree_cl := rfl
  rad_cu := rfl
  rad_cl := rfl
  rad_none := by decide
  intact := skeletonIntact_A

/-! ## 5  Arrow stoichiometry, proved -/

/-- SM → A: −2 Cl• (10 → 8). -/
theorem step_SM_A : ClCount molSM = ClCount molA + 2 := by decide
/-- A → B: −5 Cl• (8 → 3). -/
theorem step_A_B : ClCount molA = ClCount molB + 5 := by decide
/-- B → C: −2 Cl• (3 → 1). -/
theorem step_B_C : ClCount molB = ClCount molC + 2 := by decide
/-- A → D: −3 Cl• (8 → 5). -/
theorem step_A_D : ClCount molA = ClCount molD + 3 := by decide
/-- C → C₁₄ (−Cl• …, continuing to the fully dechlorinated ring;
overall chain total 10 → 0):
10 − 2 − 5 − 2 − 1 = 0. -/
theorem chain_total : 10 - 2 - 5 - 2 - 1 = 0 := by decide

/-- No carbon atom ever enters or leaves: every structure in this scheme
lives on the same 14-carbon skeleton. -/
theorem carbon_conserved : Fintype.card Skel = 14 := by decide

end IChO2026T6A2
