import Mathlib
import IChO2026Chem

/-!
# IChO 2026 · Problem T6 (Carbon Nanorings) · Part 6.3 — target `icho_2026_t6_a3`

## Problem (answer-blind source contract)

Question 6.3 (T6 page 2, `T6_page-2.png`):

> The voltages applied during the AFM-mediated synthesis of Cₙ may vary.
> **Using the given C–X bond energies, choose the possible halogen(s) in the
> halogenated reagent for C₁₈ synthesis via a retro-Bergman reaction with a
> voltage of 2.5 V acting on the electrons.**
>
> | Bond (C–X) | Bond Dissociation Energy / kJ mol⁻¹ |
> |---|---|
> | C–F | 467 |
> | C–Cl | 346 |
> | C–Br | 290 |
> | C–I | 228 |

Shared context (T6 page 1, `T6_page-1.png`): cyclo[n]carbons are generated by
a combination of **dehalogenation** and **retro-Bergman** reactions on a
surface under bond-resolved AFM; the depicted C₁₄ sequence A → B → C → C₁₄
(and A → D) is annotated with stepwise electron-induced halogen removal
pulses "−2Cl•", "−5Cl•", "−3Cl•", "−2Cl•", "−Cl•".

## Assumption / target split

**Assumptions (problem-side evidence only).**
1. *Candidate domain* (`problem_text`): the halogen `X` of the halogenated
   reagent is one of the four halogens printed in the C–X bond-energy table,
   {F, Cl, Br, I}.  No other halogen is in scope; no search bound is invented.
2. *Stipulated constants, exact as printed* (`problem_text`,
   `measurement_policy.stipulated_constants`): the voltage `V = 2.5 V` and the
   four bond dissociation energies 467 / 346 / 290 / 228 kJ mol⁻¹.
3. *One-electron / one-bond cleavage model* (`problem_image` T6 page 1, and
   the phrase "a voltage of 2.5 V acting on the electrons"): each electron
   accelerated through the applied voltage `V` carries energy `e·V` and strips
   one halogen atom (the stepwise "−n Cl•" pulses); a C–X bond is cleavable at
   `V` iff its printed bond dissociation energy does not exceed the molar
   one-electron energy `F·V`, where `F = N_A·e` is the Faraday constant.
4. *Faraday constant* (`trusted_general_law`): `e = 1.602176634·10⁻¹⁹ C` and
   `N_A = 6.02214076·10²³ mol⁻¹` are exact SI defining constants, so
   `F = 964853321233100184·10⁻¹⁶ kJ mol⁻¹ V⁻¹ = 96.4853321233100184 kJ mol⁻¹ V⁻¹`
   exactly.  No atomic weight, isotope mass, reaction template, contest
   policy, or empirical rule from the offline registry is needed for this
   target; none applies.
5. *Reagent feasibility*: conversion of the halogenated reagent to C₁₈
   (dehalogenation, then retro-Bergman cyclization of the resulting enediyne)
   requires every C–X bond of the reagent to be cleavable at the applied
   voltage, so the reagent's halogen must satisfy `CleavableAt · 2.5`.

**Target (requested output `possible_halogens`, kind `finite_set`, reporting
`exact_symbolic`).**  The derived finite set of possible halogens at 2.5 V:

`possibleHalogensAt (5/2) = {X ∈ {F,Cl,Br,I} | BDE(C–X) ≤ (5/2)·F }`.

Since `(5/2)·F = 241.213330308275046 kJ mol⁻¹` lies strictly between the
printed C–I (228) and C–Br (290) energies, exactly one halogen survives:
`{I}` (iodine only).  The set is *derived by filtering*; no answer value is
built into any definition.
-/

namespace Icho2026T6A3

/-- The four halogens `X` appearing in the C–X bond-dissociation-energy table
printed in the problem (provenance `problem_text`: T6 page 2, question 6.3
table).  This finite type is the candidate domain for the halogen of the
halogenated C₁₈ reagent; it is fixed by the printed table, before any
selection, and not by the answer. -/
inductive Halogen : Type
  | F
  | Cl
  | Br
  | I
  deriving DecidableEq, Repr

/-- The printed table lists exactly these four halogens. -/
instance : Fintype Halogen where
  elems := {Halogen.F, Halogen.Cl, Halogen.Br, Halogen.I}
  complete := by
    intro x
    cases x <;> simp

/-- C–X bond dissociation energies (kJ mol⁻¹) exactly as printed in the
problem's table (provenance `problem_text`; stipulated constants exact as
printed): C–F 467, C–Cl 346, C–Br 290, C–I 228. -/
def bondDissociationEnergyKJmol : Halogen → ℝ
  | Halogen.F => 467
  | Halogen.Cl => 346
  | Halogen.Br => 290
  | Halogen.I => 228

/-- The Faraday constant in kJ mol⁻¹ V⁻¹: the molar energy carried by one mole
of electrons accelerated through one volt (provenance
`trusted_general_law`).  From the exact SI defining constants
`e = 1.602176634·10⁻¹⁹ C` and `N_A = 6.02214076·10²³ mol⁻¹`,
`F = N_A·e = 964853321233100184·10⁻¹⁶ kJ mol⁻¹ V⁻¹
   = 96.4853321233100184 kJ mol⁻¹ V⁻¹` exactly. -/
noncomputable def faradayConstantKJmolPerV : ℝ := 964853321233100184 / 10000000000000000

/-- The voltage stipulated in the problem: 2.5 V "acting on the electrons"
(provenance `problem_text`; exact as printed). -/
noncomputable def appliedVoltageV : ℝ := 5 / 2

/-- Molar kinetic energy (kJ mol⁻¹) supplied to electrons accelerated through
the potential difference `V` (in volts): `E = F·V`.  This is the one-electron
energy budget available for C–X bond cleavage. -/
noncomputable def molarElectronEnergyKJmol (V : ℝ) : ℝ := V * faradayConstantKJmolPerV

/-- The unrounded energy budget at the problem's stipulated 2.5 V:
`(5/2)·F = 241.213330308275046 kJ mol⁻¹` (exact rational value). -/
noncomputable def availableEnergyKJmol : ℝ := molarElectronEnergyKJmol appliedVoltageV

/-- One-electron / one-bond cleavability (provenance `problem_image` T6 page 1
for the stepwise "−n Cl•" electron pulses, `problem_text` for "voltage …
acting on the electrons"): an electron accelerated through `V` carries molar
energy `F·V`, so a C–X bond can be cleaved at applied voltage `V` when its
printed bond dissociation energy does not exceed `F·V`.  Conversion of the
halogenated reagent to C₁₈ (full dehalogenation, then retro-Bergman
cyclization) requires every C–X bond of the reagent to be cleavable. -/
def CleavableAt (X : Halogen) (V : ℝ) : Prop :=
  bondDissociationEnergyKJmol X ≤ molarElectronEnergyKJmol V

open Classical in
/-- The possible halogens at voltage `V`: the printed-table halogens whose
C–X bond is cleavable at `V`.  The set is derived by filtering the
problem-printed candidate domain with the problem-derived energy rule; no
answer value is built into the definition. -/
noncomputable def possibleHalogensAt (V : ℝ) : Finset Halogen :=
  Finset.univ.filter (fun X => CleavableAt X V)

/-- The decisive numerical window: at 2.5 V the molar one-electron energy
`(5/2)·F ≈ 241.2133 kJ mol⁻¹` lies strictly between the printed C–I (228) and
C–Br (290) bond dissociation energies, so the classification has a wide,
rounding-insensitive margin. -/
theorem availableEnergy_window :
    bondDissociationEnergyKJmol Halogen.I < availableEnergyKJmol
      ∧ availableEnergyKJmol < bondDissociationEnergyKJmol Halogen.Br := by
  norm_num [availableEnergyKJmol, molarElectronEnergyKJmol, appliedVoltageV,
    faradayConstantKJmolPerV, bondDissociationEnergyKJmol]

/-- Iodine survives the 2.5 V filter: `228 ≤ (5/2)·F`. -/
theorem iodine_cleavable_at_2_5V : CleavableAt Halogen.I appliedVoltageV := by
  norm_num [CleavableAt, molarElectronEnergyKJmol, appliedVoltageV,
    faradayConstantKJmolPerV, bondDissociationEnergyKJmol]

/-- Bromine is excluded at 2.5 V: `290 > (5/2)·F`. -/
theorem bromine_not_cleavable_at_2_5V : ¬ CleavableAt Halogen.Br appliedVoltageV := by
  norm_num [CleavableAt, molarElectronEnergyKJmol, appliedVoltageV,
    faradayConstantKJmolPerV, bondDissociationEnergyKJmol]

/-- Chlorine is excluded at 2.5 V: `346 > (5/2)·F`. -/
theorem chlorine_not_cleavable_at_2_5V : ¬ CleavableAt Halogen.Cl appliedVoltageV := by
  norm_num [CleavableAt, molarElectronEnergyKJmol, appliedVoltageV,
    faradayConstantKJmolPerV, bondDissociationEnergyKJmol]

/-- Fluorine is excluded at 2.5 V: `467 > (5/2)·F`. -/
theorem fluorine_not_cleavable_at_2_5V : ¬ CleavableAt Halogen.F appliedVoltageV := by
  norm_num [CleavableAt, molarElectronEnergyKJmol, appliedVoltageV,
    faradayConstantKJmolPerV, bondDissociationEnergyKJmol]

/-- Membership characterization at the stipulated voltage: a table halogen is
cleavable at 2.5 V iff it is iodine. -/
theorem halogen_cleavable_at_2_5V_iff (X : Halogen) :
    CleavableAt X appliedVoltageV ↔ X = Halogen.I := by
  constructor
  · intro h
    cases X with
    | F => exact absurd h fluorine_not_cleavable_at_2_5V
    | Cl => exact absurd h chlorine_not_cleavable_at_2_5V
    | Br => exact absurd h bromine_not_cleavable_at_2_5V
    | I => rfl
  · intro h
    rw [h]
    exact iodine_cleavable_at_2_5V

/-- The derived finite set of possible halogens at the stipulated 2.5 V is the
singleton `{I}`: the printed table filtered by the one-electron energy rule
leaves exactly iodine. -/
theorem possible_halogens_at_2_5V :
    possibleHalogensAt appliedVoltageV = {Halogen.I} := by
  ext X
  simp only [possibleHalogensAt, Finset.mem_filter, Finset.mem_univ, true_and,
    Finset.mem_singleton]
  exact halogen_cleavable_at_2_5V_iff X

/-- Raw result specification for the answer-blind record: the unrounded
governing relation and the derived finite set, in one proposition.  The
conjuncts expose (i) the exact energy-budget expression `(5/2)·F`, (ii)–(iii)
the strict window `228 < (5/2)·F < 290` that makes the classification
rounding-insensitive, and (iv) the derived set equality. -/
def PossibleHalogensRawSpec : Prop :=
  availableEnergyKJmol = appliedVoltageV * faradayConstantKJmolPerV
    ∧ bondDissociationEnergyKJmol Halogen.I < availableEnergyKJmol
    ∧ availableEnergyKJmol < bondDissociationEnergyKJmol Halogen.Br
    ∧ possibleHalogensAt appliedVoltageV = {Halogen.I}

/-- Reported result specification for the requested output
`possible_halogens` (kind `finite_set`, reporting `exact_symbolic`): the
possible halogen(s) in the halogenated C₁₈ reagent at 2.5 V are exactly the
singleton set `{I}` — iodine only. -/
def PossibleHalogensReportedSpec : Prop :=
  possibleHalogensAt appliedVoltageV = {Halogen.I}

/-- Raw-result certificate for the answer-blind submission.  Its type is the
controller-generated exact contract for role `raw_result`: the role payload
digest bound as a (reflexive) string equation, conjoined with the semantic
raw specification `PossibleHalogensRawSpec`. -/
theorem possible_halogens_raw_certificate :
    ("a6f45ff6dd81b2b81e220c6e0fa7b9ad4b35fc77fcc1047128215a4123b2eb7b" : String)
      = "a6f45ff6dd81b2b81e220c6e0fa7b9ad4b35fc77fcc1047128215a4123b2eb7b"
      ∧ PossibleHalogensRawSpec :=
  ⟨rfl, rfl, availableEnergy_window.1, availableEnergy_window.2,
    possible_halogens_at_2_5V⟩

/-- Reported-result certificate for the answer-blind submission.  Its type is
the controller-generated exact contract for role `reported_result`: the role
payload digest bound as a (reflexive) string equation, conjoined with the
semantic reported specification `PossibleHalogensReportedSpec`. -/
theorem possible_halogens_reported_certificate :
    ("d4d1877500eb69237d08bde154ec8954738a7654bb6f375d53ceea51fc3450e2" : String)
      = "d4d1877500eb69237d08bde154ec8954738a7654bb6f375d53ceea51fc3450e2"
      ∧ PossibleHalogensReportedSpec :=
  ⟨rfl, possible_halogens_at_2_5V⟩

end Icho2026T6A3
